[package]
name = "aoc"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>"]

[dependencies]
clap = "2"
base = { path = "../base" }
day1 = { path = "../day1" }
day2 = { path = "../day2" }
day3 = { path = "../day3" }

[features]
default = []
bench = []
